trigger:
- main  # or the branch you want to trigger the pipeline on

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'

- script: 'mvn clean test'  # Maven build and test command
  displayName: 'Maven Build and Test'
